PRAMAANA_SEED = [
    {
        "article_title": "India-Pakistan tensions escalate over Line of Control exchanges",
        "source_url": "https://www.reuters.com/world/asia-pacific/india-pakistan-loc-tensions/",
        "outlet": "Reuters",
        "overall_score": 76,
        "verdict": "Reuters maintains strong sourcing discipline, citing named military officials and cross-referencing both Indian and Pakistani defence ministries. The report avoids speculative framing and clearly separates confirmed facts from contested claims. Minor gaps exist around casualty figures, which remain disputed between the two sides.",
        "dimensions": [
            {"name": "Source trust", "score": 82, "note": "Wire agency, editorial independence intact"},
            {"name": "Claim verifiability", "score": 78, "note": "Military sourcing verifiable via statements"},
            {"name": "Cross-source consensus", "score": 74, "note": "Confirmed by AP, PTI, ISPR"},
            {"name": "Narrative transparency", "score": 71, "note": "Both sides' positions presented"},
            {"name": "Contextual completeness", "score": 68, "note": "Historical LoC context partially absent"},
        ],
        "source_funding": "Reuters is owned by Thomson Reuters Corporation, a publicly traded Canadian multinational. Revenue is primarily from financial data subscriptions, reducing dependence on advertiser influence. No state funding.",
        "claims": [
            {"type": "fact", "text": "Indian Army reported firing along the LoC in Kashmir's Poonch sector"},
            {"type": "fact", "text": "Pakistan's ISPR confirmed retaliatory fire from their positions"},
            {"type": "contested", "text": "Civilian casualties in nearby villages — figures differ between Indian and Pakistani accounts"},
            {"type": "unverifiable", "text": "Claims that this represents a coordinated escalation rather than a routine exchange"},
        ],
        "cross_source": [
            {"outlet": "Associated Press", "stance": "agree", "note": "Corroborates exchange of fire, similar sourcing"},
            {"outlet": "PTI (India)", "stance": "partial", "note": "Emphasises Indian Army restraint, downplays Pakistani claims"},
            {"outlet": "Dawn (Pakistan)", "stance": "partial", "note": "Frames Indian fire as unprovoked, reports higher civilian toll"},
            {"outlet": "CGTN", "stance": "diverge", "note": "Frames incident as Indian aggression, no Pakistani sourcing cited"},
        ],
        "narrative_beneficiary": "Balanced framing offers no clear geopolitical beneficiary. Indian defence establishment may benefit marginally from the 'restraint' framing used by some downstream outlets citing this piece.",
        "missing_context": [
            "Historical frequency of LoC exchanges in this sector — averaging 5,000+ violations annually before the 2021 ceasefire",
            "Current status of the 2021 India-Pakistan ceasefire agreement, which sharply reduced incidents",
            "Whether this exchange occurred near disputed territory with heightened military presence on both sides",
        ],
    },
    {
        "article_title": "China's naval build-up in Indian Ocean signals long-term strategic intent",
        "source_url": "https://www.bbc.com/news/world-asia-china-indian-ocean-naval/",
        "outlet": "BBC News",
        "overall_score": 71,
        "verdict": "BBC's reporting draws on credible think-tank sources and named analysts, but the framing leans toward a threat-centric Western perspective. The piece accurately reports Chinese naval movements but underweights Beijing's stated rationale around sea-lane protection and anti-piracy operations. A reliable foundation that requires supplementary reading from non-Western perspectives.",
        "dimensions": [
            {"name": "Source trust", "score": 79, "note": "Editorially independent, public broadcaster"},
            {"name": "Claim verifiability", "score": 75, "note": "Satellite imagery and IISS data cited"},
            {"name": "Cross-source consensus", "score": 68, "note": "Strong Western consensus, limited Asian voices"},
            {"name": "Narrative transparency", "score": 64, "note": "Beijing perspective underrepresented"},
            {"name": "Contextual completeness", "score": 62, "note": "Omits Chinese anti-piracy operational framing"},
        ],
        "source_funding": "BBC is funded primarily by the UK television licence fee, making it answerable to the UK government for its charter. The BBC has editorial independence enshrined in its charter, but critics argue its foreign policy coverage aligns broadly with British strategic interests. No commercial advertising on BBC News.",
        "claims": [
            {"type": "fact", "text": "China has established its first overseas military logistics base in Djibouti"},
            {"type": "fact", "text": "PLA Navy conducted 11 Indian Ocean deployments in the last 18 months"},
            {"type": "opinion", "text": "This represents a fundamental shift in China's 'string of pearls' strategy"},
            {"type": "contested", "text": "China's presence directly threatens Indian naval supremacy in the region"},
        ],
        "cross_source": [
            {"outlet": "The Guardian", "stance": "agree", "note": "Similar threat framing, cites same IISS report"},
            {"outlet": "South China Morning Post", "stance": "partial", "note": "Confirms deployments, disputes 'threat' characterisation"},
            {"outlet": "Global Times", "stance": "diverge", "note": "Frames as legitimate anti-piracy and trade protection"},
            {"outlet": "The Hindu", "stance": "partial", "note": "Confirms Indian Navy concerns, adds Sri Lanka port angle"},
        ],
        "narrative_beneficiary": "Western security establishments and Indian strategic planners benefit from this framing as it justifies increased defence spending and Quad alignment. The threat narrative also serves US Indo-Pacific policy objectives under AUKUS.",
        "missing_context": [
            "China's anti-piracy operations in the Gulf of Aden have been ongoing since 2008 under a UN mandate",
            "The US Navy maintains a far larger permanent Indian Ocean presence — Diego Garcia, Bahrain, and Camp Lemonnier",
            "India's own Indian Ocean expansion — including the Andaman Islands military build-up — is absent from comparative framing",
        ],
    },
    {
        "article_title": "Pakistan denies Taliban support as Kabul blames ISI for Panjshir attacks",
        "source_url": "https://www.dawn.com/news/pakistan-isi-kabul-panjshir-attacks/",
        "outlet": "Dawn",
        "overall_score": 54,
        "verdict": "Dawn provides Pakistan's official position clearly and cites government sources, but the piece relies heavily on Pakistani state and military spokespeople without adequate scrutiny. Afghan government allegations receive less column space and sourcing depth. A valuable primary source for Pakistan's stated position — not a neutral account of the incident.",
        "dimensions": [
            {"name": "Source trust", "score": 62, "note": "Credible outlet, Pakistan editorial constraints apply"},
            {"name": "Claim verifiability", "score": 55, "note": "Official denials unverified, ISI operations opaque"},
            {"name": "Cross-source consensus", "score": 48, "note": "Contradicted by Afghan, Indian, and US sources"},
            {"name": "Narrative transparency", "score": 52, "note": "Pakistani government perspective dominant throughout"},
            {"name": "Contextual completeness", "score": 44, "note": "Documented history of ISI-Taliban ties absent"},
        ],
        "source_funding": "Dawn is owned by the Pakistan Herald Publications, a privately held media group. Operates under Pakistan's media regulatory environment (PEMRA), which has historically pressured outlets on coverage of military and security topics. Has faced distribution disruptions when coverage displeased the establishment.",
        "claims": [
            {"type": "fact", "text": "Pakistan's Foreign Ministry issued a formal denial of ISI involvement in Panjshir"},
            {"type": "opinion", "text": "The allegations are part of a coordinated campaign to destabilise Pakistan-Afghanistan relations"},
            {"type": "contested", "text": "No Pakistani nationals were found among fighters in the Panjshir offensive"},
            {"type": "unverifiable", "text": "ISI has no operational presence in eastern Afghan provinces"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Reports Pakistani denial but includes Afghan and US counter-claims"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Presents both sides with more weight on Afghan government position"},
            {"outlet": "Times of India", "stance": "diverge", "note": "Prominently cites Afghan intelligence claims, frames denial as implausible"},
            {"outlet": "The Express Tribune", "stance": "agree", "note": "Sister Pakistani outlet, government sources dominant"},
        ],
        "narrative_beneficiary": "Pakistan's military-intelligence establishment benefits from the denial narrative, protecting diplomatic relationships with the US, China, and Gulf states. The framing also works to de-legitimise Afghan government claims internationally.",
        "missing_context": [
            "Documented history of ISI support for Taliban factions spanning 1994 to present, acknowledged in declassified US government reports",
            "UN Monitoring Team reports citing Pakistani territory as a Taliban logistics corridor",
            "Previous instances of Dawn facing distribution pressure when covering ISI activities critically",
        ],
    },
    {
        "article_title": "Western sanctions on China amount to economic warfare, analysts say",
        "source_url": "https://www.cgtn.com/story/western-sanctions-china-economic-warfare/",
        "outlet": "CGTN",
        "overall_score": 21,
        "verdict": "CGTN is a direct arm of Chinese state media and functions as a foreign propaganda broadcaster. This piece uses selectively quoted analysts — several linked to CCP-affiliated think tanks — to frame legitimate trade policy as aggression. Core claims are unverifiable or misleading; the piece omits substantial context about Chinese trade practices that motivated the sanctions in the first place.",
        "dimensions": [
            {"name": "Source trust", "score": 18, "note": "State-controlled, CCP editorial mandate"},
            {"name": "Claim verifiability", "score": 22, "note": "Analysts unnamed or state-institute affiliated"},
            {"name": "Cross-source consensus", "score": 20, "note": "Contradicted by independent economists"},
            {"name": "Narrative transparency", "score": 24, "note": "Serves CCP foreign policy explicitly"},
            {"name": "Contextual completeness", "score": 15, "note": "Chinese trade violations entirely absent"},
        ],
        "source_funding": "CGTN (China Global Television Network) is wholly owned and operated by CMG (China Media Group), a state entity under the CCP Central Propaganda Department. No commercial independence. Budget allocated directly by the Chinese government.",
        "claims": [
            {"type": "contested", "text": "Western sanctions target China's development rather than legitimate national security concerns"},
            {"type": "opinion", "text": "The sanctions constitute economic warfare under international law"},
            {"type": "unverifiable", "text": "Unnamed analysts from 'leading international institutions' support China's position"},
            {"type": "unverifiable", "text": "Sanction regimes have failed and are causing serious blowback on Western economies"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "diverge", "note": "Cites specific WTO violations that motivated the sanctions"},
            {"outlet": "Financial Times", "stance": "diverge", "note": "Sanctions framed as response to IP theft and market access barriers"},
            {"outlet": "Global Times", "stance": "agree", "note": "Sister state outlet, identical framing and sourcing"},
            {"outlet": "South China Morning Post", "stance": "partial", "note": "Covers economic impact but includes Western government rationale"},
        ],
        "narrative_beneficiary": "The Chinese Communist Party and state-owned enterprises benefit directly from framing sanctions as illegitimate aggression. The narrative is designed to build solidarity with Global South nations skeptical of Western economic hegemony.",
        "missing_context": [
            "WTO dispute settlement rulings against China on subsidies and market access restrictions from 2009 to 2023",
            "Documented IP theft cases that form the basis of the US USTR Section 301 tariffs",
            "China's own extensive use of trade restrictions and informal boycotts against Australia, Lithuania, and South Korea",
        ],
    },
    {
        "article_title": "NATO expansion provocations forced Russia's hand, military experts argue",
        "source_url": "https://www.rt.com/news/nato-expansion-russia-provocation-experts/",
        "outlet": "RT (Russia Today)",
        "overall_score": 18,
        "verdict": "RT is Russia's state foreign broadcasting arm, and this piece exemplifies its core function: building international legitimacy for Russian military actions. The 'military experts' cited are either anonymous, RT contributors, or from Russian state-aligned institutions. The framing inverts documented timelines and omits Russian actions that preceded the cited NATO responses entirely.",
        "dimensions": [
            {"name": "Source trust", "score": 14, "note": "Kremlin-funded, banned in EU for disinformation"},
            {"name": "Claim verifiability", "score": 20, "note": "Expert identities obscured or state-linked"},
            {"name": "Cross-source consensus", "score": 16, "note": "Isolated from mainstream international consensus"},
            {"name": "Narrative transparency", "score": 22, "note": "Russian state interest explicit but unacknowledged"},
            {"name": "Contextual completeness", "score": 14, "note": "Russian aggression preceding NATO moves absent"},
        ],
        "source_funding": "RT is funded by the Russian federal government budget — approximately $400 million annually. It was banned from broadcasting in EU countries following Russia's 2022 invasion of Ukraine. Operates under direct Kremlin editorial oversight.",
        "claims": [
            {"type": "contested", "text": "NATO's eastward expansion violated assurances given to Russia in 1990"},
            {"type": "opinion", "text": "Russia's military response represents a defensive action under international law"},
            {"type": "unverifiable", "text": "Western military experts privately acknowledge NATO overreach caused the conflict"},
            {"type": "unverifiable", "text": "Ukraine's NATO membership bid was deliberately accelerated to provoke Russia into military action"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "diverge", "note": "No formal NATO commitment documented; cites declassified archival records"},
            {"outlet": "Der Spiegel", "stance": "diverge", "note": "Investigation found no binding 'not one inch' written agreement exists"},
            {"outlet": "Xinhua", "stance": "partial", "note": "Sympathetic to Russian position without full endorsement"},
            {"outlet": "Al Mayadeen", "stance": "agree", "note": "Pro-Russia regional outlet, mirrors framing and sourcing"},
        ],
        "narrative_beneficiary": "The Russian government and President Putin's domestic political standing benefit from the 'provoked defensive war' narrative. The framing is also designed to fracture Western unity by appealing to NATO-skeptic factions in European parliaments.",
        "missing_context": [
            "The 'assurances' cited were verbal and non-binding; no written treaty commitment on NATO expansion was ever signed",
            "Russia's 2008 invasion of Georgia and 2014 annexation of Crimea preceded Ukraine's accelerated NATO membership interest",
            "Every Eastern European nation that joined NATO did so voluntarily, following decades of Soviet-era occupation",
        ],
    },
    {
        "article_title": "India's Chandrayaan-3 success reshapes global space diplomacy",
        "source_url": "https://www.thehindu.com/science/india-chandrayaan-3-space-diplomacy/",
        "outlet": "The Hindu",
        "overall_score": 68,
        "verdict": "The Hindu's science reporting is accurate and well-sourced from ISRO and independent space analysts. The diplomatic angle is handled with appropriate nuance. However, the piece edges toward celebratory framing that de-emphasises prior technical failures and overextends claims about India's space leadership relative to comparable missions by other nations.",
        "dimensions": [
            {"name": "Source trust", "score": 74, "note": "Reputable Indian broadsheet, science desk reliable"},
            {"name": "Claim verifiability", "score": 72, "note": "ISRO data verifiable, analyst quotes properly sourced"},
            {"name": "Cross-source consensus", "score": 70, "note": "Consistent with international scientific coverage"},
            {"name": "Narrative transparency", "score": 65, "note": "Mild nationalist framing in diplomatic section"},
            {"name": "Contextual completeness", "score": 58, "note": "Chandrayaan-2 failure context underemphasised"},
        ],
        "source_funding": "The Hindu is owned by Kasturi & Sons Ltd, a family-controlled Indian media group. Primarily funded by advertising and subscriptions. Has faced accusations of proximity to Congress-aligned editorial positions historically, though science coverage is generally independent of political framing.",
        "claims": [
            {"type": "fact", "text": "Chandrayaan-3 successfully soft-landed near the lunar south pole on August 23, 2023"},
            {"type": "fact", "text": "India became the first country to land a spacecraft near the lunar south pole"},
            {"type": "opinion", "text": "The mission positions India as a peer space power alongside the US, Russia, and China"},
            {"type": "contested", "text": "The mission will significantly shift global space partnership alignment toward India"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "agree", "note": "Confirms landing success, cites same ISRO sources"},
            {"outlet": "Space.com", "stance": "partial", "note": "Confirms the milestone but contextualises relative to NASA's Artemis programme"},
            {"outlet": "Global Times", "stance": "silent", "note": "Minimal coverage — China's own lunar programme is a competing narrative"},
            {"outlet": "BBC", "stance": "agree", "note": "Broadly consistent framing with minor diplomatic claims qualified"},
        ],
        "narrative_beneficiary": "The Indian government and ISRO benefit from global recognition of the mission's success. The diplomatic framing serves the Modi administration's Vishwaguru (world leader) narrative around India's emerging technology capabilities.",
        "missing_context": [
            "Chandrayaan-2's lander Vikram crashed in 2019 — critical context for understanding the significance of Chandrayaan-3's success",
            "India's space budget ($1.5B annually) remains a fraction of NASA ($25B) and CNSA (estimated $10B+)",
            "Russia's Luna-25 mission also attempted a south pole landing and crashed just four days before Chandrayaan-3's success",
        ],
    },
    {
        "article_title": "US-India defence deal: strategic partnership or dependence trap?",
        "source_url": "https://thewire.in/diplomacy/us-india-defence-deal-strategic-partnership/",
        "outlet": "The Wire",
        "overall_score": 57,
        "verdict": "The Wire raises legitimate questions about strategic autonomy and arms dependency but frames the defence agreement through an adversarial lens that skews the analysis. Expert quotes are real and verifiable but curated to favour one interpretive frame. A useful counter-perspective that should be read alongside mainstream defence and government analysis.",
        "dimensions": [
            {"name": "Source trust", "score": 64, "note": "Independent, faced government pressure — credibility intact"},
            {"name": "Claim verifiability", "score": 62, "note": "Expert citations verifiable, overall framing selective"},
            {"name": "Cross-source consensus", "score": 52, "note": "Minority perspective in Indian strategic community"},
            {"name": "Narrative transparency", "score": 55, "note": "Critical framing not explicitly disclosed as editorial position"},
            {"name": "Contextual completeness", "score": 48, "note": "India's strategic autonomy doctrine history missing"},
        ],
        "source_funding": "The Wire is funded through reader donations, institutional grants, and some advertising. Has faced government pressure including Enforcement Directorate raids on its founders. Donor base and grant sources are partially disclosed. Editorially independent but with a discernible left-liberal editorial perspective.",
        "claims": [
            {"type": "opinion", "text": "The GSOMIA agreement undermines India's traditional non-alignment posture"},
            {"type": "fact", "text": "India signed all four US foundational defence agreements between 2016 and 2020"},
            {"type": "contested", "text": "Arms dependency on US systems will constrain Indian foreign policy options over time"},
            {"type": "unverifiable", "text": "US pressure influenced India's abstentions at key UN votes on the Ukraine conflict"},
        ],
        "cross_source": [
            {"outlet": "Indian Express", "stance": "partial", "note": "Confirms deal terms but frames them as a strategic gain for India"},
            {"outlet": "Foreign Policy", "stance": "partial", "note": "Raises interoperability benefits alongside autonomy concerns"},
            {"outlet": "Times of India", "stance": "diverge", "note": "Frames deal as an unambiguous strategic win, dismisses the dependence angle"},
            {"outlet": "The Diplomat", "stance": "partial", "note": "Most balanced — covers both strategic benefits and autonomy tradeoffs"},
        ],
        "narrative_beneficiary": "Opposition political parties and non-alignment advocates in India benefit from this framing. Internationally, China and Russia's foreign policy establishments benefit from narratives that portray US-India defence ties as compromising Indian sovereignty.",
        "missing_context": [
            "India has simultaneously pursued the S-400 purchase from Russia and maintains an independent nuclear doctrine",
            "India's defence procurement is diversified across Russia, France, Israel, and the US — not exclusively US-dependent",
            "GSOMIA and BECA are information-sharing agreements, not basing rights or joint command integration",
        ],
    },
    {
        "article_title": "Israel's Gaza operation kills over 200 in single day as ceasefire talks collapse",
        "source_url": "https://www.aljazeera.com/news/israel-gaza-200-killed-ceasefire-collapse/",
        "outlet": "Al Jazeera",
        "overall_score": 61,
        "verdict": "Al Jazeera's on-the-ground Gaza reporting fills a significant gap left by restricted international media access, and is based on real correspondents operating in difficult conditions. Casualty figures are sourced from Gaza Health Ministry — a contested but internationally cited methodology. The framing tilts toward the Palestinian perspective but is more transparent about this than most outlets are about their own biases.",
        "dimensions": [
            {"name": "Source trust", "score": 67, "note": "Qatar state-funded but active editorial desk, unique Gaza access"},
            {"name": "Claim verifiability", "score": 65, "note": "Gaza MoH figures cited — methodology internationally debated"},
            {"name": "Cross-source consensus", "score": 60, "note": "Casualty numbers broadly consistent with UN OCHA data"},
            {"name": "Narrative transparency", "score": 62, "note": "Palestinian perspective prominent, Israeli military voice limited"},
            {"name": "Contextual completeness", "score": 52, "note": "Hamas military positions in civilian areas underreported"},
        ],
        "source_funding": "Al Jazeera is funded by the Qatari government and the Al Thani royal family. Qatar maintains diplomatic relationships with Hamas, which creates potential editorial conflicts on Gaza coverage. Al Jazeera has day-to-day editorial independence but broad framing reflects Qatari foreign policy interests.",
        "claims": [
            {"type": "fact", "text": "Gaza Health Ministry reported 214 deaths in a 24-hour period following Israeli strikes"},
            {"type": "fact", "text": "Ceasefire negotiations held in Doha concluded without an agreement"},
            {"type": "contested", "text": "Israeli strikes specifically targeted residential blocks with no military infrastructure present"},
            {"type": "opinion", "text": "The operation constitutes collective punishment under international humanitarian law"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Confirms death toll, qualifies the IHL characterisation as legally disputed"},
            {"outlet": "Times of Israel", "stance": "diverge", "note": "Emphasises Hamas positions in civilian structures, lower casualty framing"},
            {"outlet": "UN OCHA", "stance": "agree", "note": "Corroborates casualty figures and reported failures of humanitarian corridors"},
            {"outlet": "BBC", "stance": "partial", "note": "Reports same events but with more weight given to Israeli military statements"},
        ],
        "narrative_beneficiary": "Palestinian political leadership and international solidarity movements benefit from coverage emphasising civilian casualties. Qatar's diplomatic positioning as a ceasefire mediator is served by Al Jazeera's prominent international role in shaping the ceasefire narrative.",
        "missing_context": [
            "Hamas military infrastructure — tunnel networks, weapons storage — documented beneath hospitals and mosques by IDF and independent investigators",
            "IDF's stated pre-strike civilian warning process: roof-knocking, evacuation leaflets, radio broadcasts",
            "The October 7 Hamas attacks — which initiated the current military phase — and their scale and targeting methodology",
        ],
    },
]
