PRAMAANA_SEED = [
    # ── High credibility ────────────────────────────────────────────────────
    {
        "article_title": "Operation Sindoor and the Evolution of India's Military Strategy Against Pakistan",
        "source_url": "https://warontherocks.com/2025/05/operation-sindoor-and-the-evolution-of-indias-strategy-against-pakistan/",
        "outlet": "War on the Rocks",
        "overall_score": 74,
        "verdict": "War on the Rocks is a peer-reviewed defence policy outlet with strong editorial standards. This piece by Arzan Tarapore traces India's strategic evolution across Uri, Balakot, and Operation Sindoor with credible sourcing and analytical restraint. The framing is Western-security-establishment adjacent, which slightly underweights Pakistani and civilian perspectives, but the core analysis is rigorously argued.",
        "dimensions": [
            {"name": "Source trust", "score": 81, "note": "Peer-reviewed defence journal, named expert author"},
            {"name": "Claim verifiability", "score": 78, "note": "Historical events cited are verifiable and documented"},
            {"name": "Cross-source consensus", "score": 72, "note": "Core thesis consistent with Indian strategic literature"},
            {"name": "Narrative transparency", "score": 70, "note": "Analytical framing, US-aligned security perspective"},
            {"name": "Contextual completeness", "score": 66, "note": "Pakistani civilian impact underexplored"},
        ],
        "source_funding": "War on the Rocks is an independent US-based defence and national security journal funded through subscriptions, institutional partnerships, and reader donations. It has no government or defence contractor funding and maintains an editorial firewall. Authors publish in their individual capacities.",
        "claims": [
            {"type": "fact", "text": "India launched Operation Sindoor on May 7, 2025, striking nine sites in Pakistan and Pakistan-administered Kashmir"},
            {"type": "fact", "text": "The operation was India's response to the Pahalgam terror attack of April 22, 2025, which killed 26 civilians"},
            {"type": "opinion", "text": "Operation Sindoor represents a decisive shift from deterrence-by-punishment to degradation-of-capacity"},
            {"type": "contested", "text": "The strike framework established a new escalation threshold that Pakistan is unlikely to challenge militarily"},
        ],
        "cross_source": [
            {"outlet": "Stimson Center", "stance": "agree", "note": "Independent US think tank corroborates the strategic evolution thesis"},
            {"outlet": "Dawn (Pakistan)", "stance": "diverge", "note": "Frames strikes as unprovoked aggression on civilian infrastructure"},
            {"outlet": "The Hindu", "stance": "partial", "note": "Confirms facts, more cautious on long-term strategic implications"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Reports operation accurately but emphasises civilian casualty claims"},
        ],
        "narrative_beneficiary": "The Indian security establishment and proponents of a more assertive Indian posture benefit from this analytical frame. The piece implicitly validates the political decision to escalate beyond the Balakot precedent.",
        "missing_context": [
            "Civilian casualty figures from Pakistani sources — disputed but not engaged with in the analysis",
            "Pakistan's domestic political constraints that shaped its military response calculus",
            "The role of US and Chinese backchannel communications in bringing about the ceasefire",
        ],
    },

    # ── Mixed credibility ────────────────────────────────────────────────────
    {
        "article_title": "Biden says Israel has agreed to 'enduring' Gaza ceasefire proposal",
        "source_url": "https://www.aljazeera.com/news/2024/5/31/biden-says-israel-has-agreed-to-enduring-gaza-ceasefire-proposal",
        "outlet": "Al Jazeera",
        "overall_score": 61,
        "verdict": "Al Jazeera's coverage of Biden's ceasefire proposal is factually grounded and fills a genuine reporting gap. The piece accurately reports the three-phase proposal and Hamas's response. However, Israeli government counter-framing receives less depth than Palestinian reaction, and the headline's framing of Israel having 'agreed' was contested within hours — a nuance the article addresses only partially.",
        "dimensions": [
            {"name": "Source trust", "score": 67, "note": "Qatar state-funded, active Gaza correspondent network"},
            {"name": "Claim verifiability", "score": 69, "note": "Biden's speech is primary source, accurately reported"},
            {"name": "Cross-source consensus", "score": 63, "note": "Proposal details confirmed by Reuters and AP"},
            {"name": "Narrative transparency", "score": 58, "note": "Palestinian framing slightly dominant over Israeli position"},
            {"name": "Contextual completeness", "score": 53, "note": "Hamas's internal divisions on accepting deal not covered"},
        ],
        "source_funding": "Al Jazeera is funded by the Qatari government and the Al Thani royal family. Qatar hosts Hamas's political leadership and serves as a key ceasefire mediator, creating a structural editorial tension on Gaza coverage. Al Jazeera operates with day-to-day editorial independence but broad framing reflects Qatari foreign policy interests.",
        "claims": [
            {"type": "fact", "text": "President Biden announced a three-phase ceasefire proposal on May 31, 2024"},
            {"type": "fact", "text": "Phase one included a six-week ceasefire and Israeli withdrawal from populated Gaza areas"},
            {"type": "contested", "text": "Israel had agreed to the proposal — Israeli officials later walked back the characterisation"},
            {"type": "opinion", "text": "The proposal represented a significant shift in US posture toward pressuring Israel"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Confirms proposal, notes Israeli ambiguity on agreement immediately"},
            {"outlet": "Times of Israel", "stance": "diverge", "note": "Emphasises Netanyahu's insistence war goals not yet achieved"},
            {"outlet": "UN OCHA", "stance": "agree", "note": "Welcomed proposal, corroborates humanitarian corridor framework"},
            {"outlet": "BBC", "stance": "partial", "note": "Similar framing but gives more weight to Israeli government statements"},
        ],
        "narrative_beneficiary": "Qatar's diplomatic positioning as a credible ceasefire mediator is served by Al Jazeera's prominent international role. Palestinian political leadership benefits from coverage that frames Israel as the obstacle to peace. Biden administration benefits from the 'US as honest broker' angle.",
        "missing_context": [
            "Hamas's internal political split between Yahya Sinwar's military wing and the Doha-based political bureau on accepting any deal",
            "The proposal had been circulating for weeks — the 'announcement' was a political move ahead of US domestic political pressure",
            "Previous ceasefire proposals had collapsed at similar stages — historical context largely absent",
        ],
    },
    {
        "article_title": "Another India-US Defence Agreement, Same Old Obstacles",
        "source_url": "https://thewire.in/article/security/another-india-us-defence-agreement-same-old-obstacles",
        "outlet": "The Wire",
        "overall_score": 57,
        "verdict": "Rahul Bedi's analysis documents a genuine pattern of underdelivery in India-US defence co-development, with verifiable references to failed programmes like DTTI and iCET. The core thesis is supported by evidence. However, the piece curates expert opinion toward scepticism and omits significant counterevidence — actual technology transfers and joint production that have occurred — creating an imbalanced picture that serves a pre-formed conclusion.",
        "dimensions": [
            {"name": "Source trust", "score": 65, "note": "Independent, faced government pressure — editorial independence intact"},
            {"name": "Claim verifiability", "score": 63, "note": "DTTI and iCET failures documented and verifiable"},
            {"name": "Cross-source consensus", "score": 54, "note": "Minority view in Indian strategic community"},
            {"name": "Narrative transparency", "score": 52, "note": "Sceptical framing not disclosed as editorial position"},
            {"name": "Contextual completeness", "score": 47, "note": "GE-414 engine deal, MQ-9B purchase omitted as counterevidence"},
        ],
        "source_funding": "The Wire is funded through reader donations, institutional grants, and limited advertising. Has faced Enforcement Directorate raids targeting its founders, widely interpreted as government pressure. Donor base partially disclosed. Editorially independent with a discernible left-liberal editorial stance on security and foreign policy.",
        "claims": [
            {"type": "fact", "text": "The Defence Technology and Trade Initiative (DTTI) launched in 2012 produced no major co-development outcomes"},
            {"type": "fact", "text": "India and the US signed the Initiative on Critical and Emerging Technologies (iCET) in 2022"},
            {"type": "opinion", "text": "The latest defence framework risks repeating the cycle of lofty intent and limited delivery"},
            {"type": "contested", "text": "US export controls (ITAR) systematically prevent meaningful technology transfer to India"},
        ],
        "cross_source": [
            {"outlet": "Indian Express", "stance": "diverge", "note": "Points to GE-414 engine deal and MQ-9B as concrete deliverables"},
            {"outlet": "The Diplomat", "stance": "partial", "note": "Acknowledges obstacles but frames recent progress as more substantive"},
            {"outlet": "Foreign Policy", "stance": "partial", "note": "Notes structural ITAR problems but more optimistic on iCET trajectory"},
            {"outlet": "Times of India", "stance": "diverge", "note": "Frames India-US defence ties as genuinely transformative under Modi"},
        ],
        "narrative_beneficiary": "Opposition voices and non-alignment advocates in India benefit from a narrative that undermines confidence in US partnership. Indirectly, Russia and China benefit from coverage that portrays US-India defence deepening as unproductive and conditional.",
        "missing_context": [
            "India signed the $3.99 billion GE-414 engine co-production deal in 2023 — the largest technology transfer in India-US defence history",
            "India's purchase of 31 MQ-9B Predator drones ($3.7B) represents a significant procurement shift not mentioned",
            "ITAR reform has been ongoing and India received STA-1 designation in 2016, facilitating more transfers than the article implies",
        ],
    },
    {
        "article_title": "Dealing with the Taliban",
        "source_url": "https://www.dawn.com/news/1884874",
        "outlet": "Dawn",
        "overall_score": 54,
        "verdict": "Maleeha Lodhi, a former Pakistani ambassador, provides a sophisticated insider account of Pakistan's Taliban dilemma that is analytically stronger than typical government-aligned commentary. She acknowledges the TTP threat honestly. However, the piece consistently frames Pakistan as reacting to circumstances rather than examining Islamabad's historical role in creating them, and avoids the structural question of ISI's relationship with the Afghan Taliban.",
        "dimensions": [
            {"name": "Source trust", "score": 62, "note": "Credible author, Dawn under periodic establishment pressure"},
            {"name": "Claim verifiability", "score": 60, "note": "TTP attack figures and diplomatic facts verifiable"},
            {"name": "Cross-source consensus", "score": 52, "note": "Pakistani framing diverges from Afghan and Western accounts"},
            {"name": "Narrative transparency", "score": 49, "note": "Pakistani state perspective dominant, historical agency absent"},
            {"name": "Contextual completeness", "score": 45, "note": "ISI-Taliban historical relationship entirely unaddressed"},
        ],
        "source_funding": "Dawn is owned by Pakistan Herald Publications, a privately held media group. Operates under PEMRA (Pakistan Electronic Media Regulatory Authority), which has a track record of pressuring outlets on coverage of military-intelligence matters. Dawn has faced distribution blockades in the past when coverage diverged from establishment preferences.",
        "claims": [
            {"type": "fact", "text": "The Tehreek-i-Taliban Pakistan (TTP) has escalated cross-border attacks from Afghan territory since 2021"},
            {"type": "fact", "text": "Pakistan and Afghanistan held multiple rounds of diplomatic talks in Istanbul in 2024–2025"},
            {"type": "opinion", "text": "Pakistan's shift to a 'carrot-and-stick' approach represents a more mature and sustainable strategy"},
            {"type": "contested", "text": "The Afghan Taliban are unwilling and unable to restrain TTP operations against Pakistan"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Corroborates TTP escalation but includes Afghan Taliban denial of Pakistani claims"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Reports Pakistan-Afghanistan tensions with more balance on responsibility"},
            {"outlet": "UN Monitoring Team", "stance": "diverge", "note": "Reports Taliban providing limited but real support to TTP — contradicts Pakistani framing"},
            {"outlet": "The Hindu", "stance": "diverge", "note": "Focuses on ISI's historical cultivation of Taliban as Pakistani strategic asset"},
        ],
        "narrative_beneficiary": "Pakistan's military-civilian establishment benefits from a framing that positions Pakistan as a victim of terrorism rather than a historical enabler. The 'carrot-and-stick' framing also serves to legitimise Pakistani airstrikes inside Afghanistan by portraying them as reluctant responses.",
        "missing_context": [
            "UN Monitoring Team reports consistently documenting Pakistani territory as a Taliban logistics and financial corridor",
            "ISI's documented cultivation of Haqqani Network and Quetta Shura Taliban as strategic assets from 2001–2021",
            "Pakistan's previous pattern of using 'negotiations' with TTP as tactical pauses rather than genuine disarmament processes",
        ],
    },
    {
        "article_title": "Uniform Civil Code: Another Step Towards Making India a Hindu Rashtra",
        "source_url": "https://frontline.thehindu.com/the-nation/uniform-civil-code-another-step-towards-making-india-a-hindu-rashtra/article67101084.ece",
        "outlet": "Frontline",
        "overall_score": 42,
        "verdict": "Frontline raises legitimate constitutional and minority rights concerns about UCC implementation, and some of the legal arguments are substantive. However, the headline's framing — 'Another Step Towards Making India a Hindu Rashtra' — is an opinion positioned as a factual trajectory, not a hypothesis. The piece consistently interprets ambiguous policy choices as evidence of civilisational project rather than engaging the government's stated secular rationale for uniform law.",
        "dimensions": [
            {"name": "Source trust", "score": 55, "note": "Established Indian magazine, left-liberal editorial history"},
            {"name": "Claim verifiability", "score": 52, "note": "Constitutional citations verifiable, policy framing contested"},
            {"name": "Cross-source consensus", "score": 42, "note": "Framing contradicted by Indian government and mainstream legal opinion"},
            {"name": "Narrative transparency", "score": 38, "note": "Opinion framing in headline presented as established trajectory"},
            {"name": "Contextual completeness", "score": 35, "note": "Government's stated constitutional rationale largely absent"},
        ],
        "source_funding": "Frontline is a fortnightly magazine published by The Hindu Group, owned by the Kasturi & Sons family trust. It has a long-standing editorial identity associated with India's left-liberal and Nehruvian traditions. Funded primarily by subscriptions and advertising. No direct state funding, but The Hindu Group has faced accusations of Congress-era proximity.",
        "claims": [
            {"type": "fact", "text": "Uttarakhand became the first state to implement UCC legislation in 2024"},
            {"type": "opinion", "text": "UCC implementation represents a deliberate step in a project to make India a Hindu Rashtra"},
            {"type": "contested", "text": "The UCC as designed will disproportionately impose Hindu personal law norms on minorities"},
            {"type": "unverifiable", "text": "The BJP's long-term intent is religious majoritarianism rather than constitutional uniformity"},
        ],
        "cross_source": [
            {"outlet": "Indian Express", "stance": "partial", "note": "Reports UCC concerns but does not adopt Hindu Rashtra framing"},
            {"outlet": "Times of India", "stance": "diverge", "note": "Frames UCC as constitutional reform consistent with Ambedkar's vision"},
            {"outlet": "The Hindu", "stance": "partial", "note": "Critical of implementation, more cautious on civilisational framing"},
            {"outlet": "Organiser (RSS)", "stance": "diverge", "note": "Frames UCC as long-overdue secular reform, cites Ambedkar and Nehru-era debates"},
        ],
        "narrative_beneficiary": "Opposition political parties, Muslim personal law boards, and international human rights organisations benefit from the Hindu Rashtra framing as it reframes a domestic legal debate as a minority rights crisis. The framing also resonates with Western audiences primed to view BJP governance through a democratic backsliding lens.",
        "missing_context": [
            "B.R. Ambedkar explicitly advocated for UCC in the Constituent Assembly as essential to modern secular governance",
            "Goa has had a UCC since the Portuguese colonial era — no UCC-implementing state has seen documented religious discrimination under it",
            "The Uttarakhand UCC was drafted by a committee that included Muslim, Christian, and tribal representatives",
        ],
    },

    # ── Low credibility ────────────────────────────────────────────────────
    {
        "article_title": "Western 'alternative' narrative detrimental to Indian infrastructure development",
        "source_url": "https://www.globaltimes.cn/page/202408/1318526.shtml",
        "outlet": "Global Times",
        "overall_score": 22,
        "verdict": "Global Times is an official organ of the Chinese Communist Party, published under People's Daily. This piece is a textbook example of CCP foreign influence strategy: using India's legitimate infrastructure ambitions to position China as India's natural partner and Western frameworks as adversarial. The 'analyst' voices are unattributed or drawn from Chinese state-adjacent think tanks. The argument is constructed to serve Beijing's geopolitical interests, not India's.",
        "dimensions": [
            {"name": "Source trust", "score": 18, "note": "CCP organ, People's Daily subsidiary, no editorial independence"},
            {"name": "Claim verifiability", "score": 22, "note": "Infrastructure claims partial; analyst attributions absent"},
            {"name": "Cross-source consensus", "score": 20, "note": "Contradicted by Indian government's own infrastructure policy"},
            {"name": "Narrative transparency", "score": 24, "note": "CCP interest in displacing Western influence not disclosed"},
            {"name": "Contextual completeness", "score": 18, "note": "China's own predatory infrastructure lending record absent"},
        ],
        "source_funding": "Global Times is published by People's Daily, the official newspaper of the Central Committee of the Communist Party of China. Fully state-funded and under direct CCP editorial control. Its English-language edition serves as a foreign-facing propaganda platform targeting international audiences.",
        "claims": [
            {"type": "opinion", "text": "Western narratives positioning India as a China alternative are designed to harm India's development"},
            {"type": "unverifiable", "text": "India's genuine interests are better served by Asian economic integration than Western frameworks"},
            {"type": "contested", "text": "Western infrastructure alternatives like G7's PGII offer less value than Asian supply chain participation"},
            {"type": "unverifiable", "text": "Western 'China+1' framing serves geopolitical containment rather than Indian economic benefit"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "diverge", "note": "India's own PLI scheme explicitly designed to attract Western firms as alternatives to China"},
            {"outlet": "Economic Times", "stance": "diverge", "note": "Documents India's deliberate policy to limit Chinese FDI and investment"},
            {"outlet": "Xinhua", "stance": "agree", "note": "Sister CCP outlet, identical framing on Western narrative containment"},
            {"outlet": "South China Morning Post", "stance": "silent", "note": "More balanced on India-China competition, does not adopt this framing"},
        ],
        "narrative_beneficiary": "The Chinese Communist Party and Chinese infrastructure firms benefit directly from undermining India's confidence in Western partnerships. The piece is part of a systematic CCP effort to prevent India from deepening economic ties with the Quad and G7 nations.",
        "missing_context": [
            "China's Belt and Road Initiative has left Sri Lanka, Pakistan, and Zambia in documented debt distress — relevant context for any India infrastructure advice from Beijing",
            "India has explicitly restricted Chinese FDI since the 2020 Galwan clashes, reflecting Indian government's own assessment of Chinese intent",
            "India's PLI (Production Linked Incentive) scheme has attracted Apple, Samsung, and dozens of Western firms — directly contradicting the article's central premise",
        ],
    },
    {
        "article_title": "WEF 2023: U.S. sanctions obsession subverts international cooperation",
        "source_url": "https://news.cgtn.com/news/2023-01-20/WEF-2023-U-S-sanctions-obsession-subverts-international-cooperation-1gKmidSxnig/index.html",
        "outlet": "CGTN",
        "overall_score": 20,
        "verdict": "CGTN is China's state international broadcasting network, operating under the CCP's Central Propaganda Department. This Davos-timed opinion piece uses the WEF's cooperation-themed agenda to delegitimise US sanctions policy — a core CCP foreign policy objective. The author selectively frames US sanctions as unilateral aggression while omitting the specific Chinese trade and security practices that triggered them. The piece is advocacy dressed as analysis.",
        "dimensions": [
            {"name": "Source trust", "score": 16, "note": "CCP-controlled foreign broadcaster, propaganda mandate"},
            {"name": "Claim verifiability", "score": 22, "note": "WEF theme cited accurately; sanctions rationale misrepresented"},
            {"name": "Cross-source consensus", "score": 18, "note": "Position contradicted by WTO rulings and allied governments"},
            {"name": "Narrative transparency", "score": 20, "note": "CCP interest in sanctions relief not acknowledged"},
            {"name": "Contextual completeness", "score": 14, "note": "Chinese IP theft and market access violations entirely absent"},
        ],
        "source_funding": "CGTN (China Global Television Network) is wholly owned and operated by CMG (China Media Group), a state entity under the CCP Central Propaganda Department. Approximately $2 billion in annual government funding. Banned from broadcasting in the UK in 2021 over content control violations. No editorial independence from Chinese state.",
        "claims": [
            {"type": "opinion", "text": "US sanctions policy contradicts the WEF's stated theme of cooperation in a fragmented world"},
            {"type": "contested", "text": "US sanctions on China target its development rather than legitimate security concerns"},
            {"type": "unverifiable", "text": "Intelligence community warnings on China are overstated to justify economic containment"},
            {"type": "unverifiable", "text": "Sanctions regimes consistently fail to achieve stated objectives and harm global stability"},
        ],
        "cross_source": [
            {"outlet": "Financial Times", "stance": "diverge", "note": "Documents specific IP theft and market access violations motivating sanctions"},
            {"outlet": "Reuters", "stance": "diverge", "note": "Reports WTO rulings against China that informed the US sanctions framework"},
            {"outlet": "Global Times", "stance": "agree", "note": "Sister CCP outlet, identical framing and narrative objectives"},
            {"outlet": "South China Morning Post", "stance": "partial", "note": "Covers tensions but includes Western government rationale for sanctions"},
        ],
        "narrative_beneficiary": "The Chinese Communist Party and Chinese state-owned enterprises are the primary beneficiaries — sanctions relief would directly benefit Chinese tech firms (Huawei, SMIC) and reduce costs of Chinese military-civil fusion programmes. The piece is timed to Davos to reach maximum elite international audience.",
        "missing_context": [
            "WTO ruled against China on subsidies and market access in over 40 disputes from 2001 to 2023 — the legal foundation for US sanctions",
            "US USTR Section 301 investigation documented $50B annually in IP theft attributable to Chinese state-sponsored actors",
            "China itself maintains extensive import restrictions, technology bans, and informal boycotts against countries that displease Beijing",
        ],
    },
    {
        "article_title": "Does Russia have a point about NATO expansion?",
        "source_url": "https://www.rt.com/russia/547775-west-europe-nato-expansion/",
        "outlet": "RT (Russia Today)",
        "overall_score": 18,
        "verdict": "RT is Russia's state foreign broadcasting arm, and while this piece is authored by a credentialled international law professor — Alfred de Zayas — its publication on RT serves a clear function: lending academic legitimacy to Russian state talking points on NATO expansion as provocation. The Kennan quote and 'assurances' argument have real scholarly debate around them, but the piece presents the most Russia-favourable version of contested history as settled fact, and was published weeks before the 2022 invasion as part of a coordinated information operation.",
        "dimensions": [
            {"name": "Source trust", "score": 14, "note": "Kremlin-funded, banned in EU and UK for disinformation"},
            {"name": "Claim verifiability", "score": 24, "note": "Kennan quote real; 'assurances' claim historically contested"},
            {"name": "Cross-source consensus", "score": 16, "note": "Isolated from mainstream historical and legal scholarship"},
            {"name": "Narrative transparency", "score": 20, "note": "Author's credentials used to mask RT's state propaganda function"},
            {"name": "Contextual completeness", "score": 14, "note": "Russian aggression timeline and Eastern European agency absent"},
        ],
        "source_funding": "RT (Russia Today) is funded by the Russian federal budget — approximately $400 million annually. It was banned from broadcasting in the EU following Russia's 2022 invasion of Ukraine and from the UK by Ofcom for editorial control violations. Operates under direct Kremlin supervision. The RT America network was shut down in 2022.",
        "claims": [
            {"type": "contested", "text": "NATO's eastward expansion violated verbal assurances given to Soviet leaders in 1990"},
            {"type": "opinion", "text": "Western provocations rather than Russian decisions caused the deterioration of European security"},
            {"type": "unverifiable", "text": "Western security experts privately acknowledge NATO expansion was a catastrophic mistake"},
            {"type": "unverifiable", "text": "Russia's concerns about NATO constitute a legitimate security interest under international law that justifies military response"},
        ],
        "cross_source": [
            {"outlet": "Der Spiegel", "stance": "diverge", "note": "Archive investigation found no binding written commitment on NATO expansion"},
            {"outlet": "Reuters", "stance": "diverge", "note": "Historical record shows no formal treaty — only informal conversations"},
            {"outlet": "Xinhua", "stance": "partial", "note": "Sympathetic to Russian framing without full endorsement"},
            {"outlet": "Le Monde Diplomatique", "stance": "partial", "note": "Acknowledges legitimate Russian security concerns but rejects invasion as justified"},
        ],
        "narrative_beneficiary": "The Russian government and Vladimir Putin's domestic political legitimacy benefit from the 'NATO provocation' narrative. The piece is designed to erode Western European public support for NATO and create false equivalence between Russian aggression and Alliance expansion. Published January 2022 — weeks before the invasion.",
        "missing_context": [
            "Every Eastern European state that joined NATO did so voluntarily after Soviet-era occupation — their agency is entirely absent from this framing",
            "Russia's 2008 invasion of Georgia and 2014 annexation of Crimea preceded Ukraine's accelerated NATO membership interest by years",
            "The 'assurances' were verbal, non-binding, and given to the Soviet Union — a state that no longer existed by the time NATO expanded",
        ],
    },
]
